In [ ]:
#check 1d-data.csv dataset

import pandas as pd
df_1d = pd.read_csv('../data/1d-data.csv')
print(df_1d.head())

          value  group
0      4.564090  cases
1   1040.947860  cases
2   3117.665150  cases
3     67.501829  cases
4  10096.092602  cases

In [7]:
df_1d.describe()

              value
count     20.000000
mean    5669.799506
std     9384.638717
min        4.564090
25%      201.628294
50%     2589.403022
75%     5662.118287
max    35764.919601

In [8]:
#check 2d-data.csv dataset

import pandas as pd
df_2d = pd.read_csv('../data/2d-data.csv')
print(df_2d.head())

          x         y
0  2.182405  2.098743
1  2.068501  2.220172
2  2.323348  1.857437
3  1.897711  2.190042
4  1.853192  2.168086

In [9]:
df_2d.describe()

                 x            y
count  6000.000000  6000.000000
mean      2.204573     2.200229
std       0.280911     0.285389
min       1.239564     1.359797
25%       1.996830     1.986037
50%       2.206386     2.195402
75%       2.410492     2.411082
max       3.100052     3.182196

In [15]:
#digits quick check
df_digits = pd.read_csv('../data/digits-data.csv')
print(df_digits.head())

   pixel_0  pixel_1  pixel_2  pixel_3  pixel_4  pixel_5  pixel_6  pixel_7  \
0      0.0      0.0      5.0     13.0      9.0      1.0      0.0      0.0
1      0.0      0.0      0.0     12.0     13.0      5.0      0.0      0.0
2      0.0      0.0      0.0      4.0     15.0     12.0      0.0      0.0
3      0.0      0.0      7.0     15.0     13.0      1.0      0.0      0.0
4      0.0      0.0      0.0      1.0     11.0      0.0      0.0      0.0

   pixel_8  pixel_9  ...  pixel_55  pixel_56  pixel_57  pixel_58  pixel_59  \
0      0.0      0.0  ...       0.0       0.0       0.0       6.0      13.0
1      0.0      0.0  ...       0.0       0.0       0.0       0.0      11.0
2      0.0      0.0  ...       0.0       0.0       0.0       0.0       3.0
3      0.0      8.0  ...       0.0       0.0       0.0       7.0      13.0
4      0.0      0.0  ...       0.0       0.0       0.0       0.0       2.0

   pixel_60  pixel_61  pixel_62  pixel_63  digit
0      10.0       0.0       0.0       0.0      0
1      16.0      10.0       0.0       0.0      1
2      11.0      16.0       9.0       0.0      2
3      13.0       9.0       0.0       0.0      3
4      16.0       4.0       0.0       0.0      4

[5 rows x 65 columns]

In [16]:
#1d multi
df_multi = pd.read_csv('../data/1d-multi-method-data.csv')
df_multi.head()

     method    AUCROC
0  Proposed  0.700433
1  Proposed  0.699677
2  Proposed  0.694899
3  Proposed  0.611460
4  Proposed  0.623799

In [18]:
#df_multi.describe()
df_multi.groupby("method")["AUCROC"].describe()

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Baseline_1,10.0,0.766974,0.028340,0.723696,0.745587,0.767523,0.785299,0.814718
Baseline_2,10.0,0.916858,0.047228,0.859022,0.879073,0.907718,0.943064,1.000000
Baseline_3,10.0,0.461854,0.025365,0.428500,0.446208,0.455904,0.484753,0.498006
Baseline_4,10.0,0.226200,0.008332,0.216170,0.219812,0.225000,0.230889,0.241037
Baseline_5,10.0,0.269172,0.015902,0.251466,0.256842,0.266379,0.279422,0.296873
Baseline_6,10.0,0.320925,0.016698,0.298497,0.306709,0.323728,0.334664,0.341329
Baseline_7,10.0,0.388454,0.012179,0.368384,0.381266,0.391778,0.396870,0.402152
Baseline_8,10.0,0.192495,0.011256,0.177354,0.185302,0.191516,0.202850,0.208932
Baseline_9,10.0,0.557234,0.035440,0.502816,0.522701,0.572660,0.586813,0.593619
Proposed,10.0,0.661321,0.036766,0.610155,0.628528,0.669363,0.694010,0.700433