In [ ]:
#check 1d-data.csv dataset

import pandas as pd
df_1d = pd.read_csv('../data/1d-data.csv')
print(df_1d.head())

          value  group
0      4.564090  cases
1   1040.947860  cases
2   3117.665150  cases
3     67.501829  cases
4  10096.092602  cases

In [7]:
df_1d.describe()

              value
count     20.000000
mean    5669.799506
std     9384.638717
min        4.564090
25%      201.628294
50%     2589.403022
75%     5662.118287
max    35764.919601

In [8]:
#check 2d-data.csv dataset

import pandas as pd
df_2d = pd.read_csv('../data/2d-data.csv')
print(df_2d.head())

          x         y
0  2.182405  2.098743
1  2.068501  2.220172
2  2.323348  1.857437
3  1.897711  2.190042
4  1.853192  2.168086

In [9]:
df_2d.describe()

                 x            y
count  6000.000000  6000.000000
mean      2.204573     2.200229
std       0.280911     0.285389
min       1.239564     1.359797
25%       1.996830     1.986037
50%       2.206386     2.195402
75%       2.410492     2.411082
max       3.100052     3.182196